# Generated by Django 4.0.6 on 2022-07-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='account',
        ),
    ]
