# Generated by Django 4.0.6 on 2022-07-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_company_contact_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='products',
            field=models.ManyToManyField(to='main_app.product'),
        ),
    ]
