# Generated by Django 4.0.6 on 2022-07-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_contact_phone'),
        ('main_app', '0005_remove_product_account_account_products'),
    ]

    operations = [
    ]
