# Generated by Django 4.0.6 on 2022-07-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='serial_number',
            field=models.CharField(default='2aa5af', max_length=100),
        ),
    ]
