# Generated by Django 4.0.6 on 2022-07-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_transactions_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
