# Generated by Django 4.0.6 on 2022-07-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_transactions_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='serial_number',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('P', 'In Progress'), ('I', 'Incomplete'), ('C', 'Completed')], default='P', max_length=1),
        ),
    ]
